<?php

use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table = DB::table('course');
        
        //$data = $this->getData();
        
        $table->insert(
    	[
        	['code' => '001001', 'description' => 'Pre-School/Elementary'], 
			['code' => '001002', 'description' => 'Secondary'], 
			['code' => '001003', 'description' => 'Arts'], 
			['code' => '001004', 'description' => 'Science'], 
			['code' => '001005', 'description' => 'Liberal Arts-Liacom'], 
			['code' => '001006', 'description' => 'Pre-Dental'], 
			['code' => '001007', 'description' => 'Letters'], 
			['code' => '001008', 'description' => 'Professional Studies'], 
			['code' => '140101', 'description' => 'Elementary Education'], 
			['code' => '140102', 'description' => 'Secondary Education with no specialization'], 
			['code' => '140104', 'description' => 'Elementary and Secondary Education w/ no specialization'], 
			['code' => '140106', 'description' => 'Pedagogy'], 
			['code' => '140108', 'description' => 'Education'], 
			['code' => '140109', 'description' => 'Teaching'], 
			['code' => '140110', 'description' => 'Educational Foundation'], 
			['code' => '140401', 'description' => 'Chemistry Education'], 
			['code' => '140402', 'description' => 'Christian Education'], 
			['code' => '140403', 'description' => 'English Education'], 
			['code' => '140404', 'description' => 'Mathematics Teaching'], 
			['code' => '140405', 'description' => 'Physics Teaching'], 
			['code' => '140406', 'description' => 'Religious Education (Character/Value Education)'], 
			['code' => '140407', 'description' => 'Arabic Education (teaching Arabic)'], 
			['code' => '140408', 'description' => 'Physical Education'], 
			['code' => '140409', 'description' => 'Biology Education'], 
			['code' => '140410', 'description' => 'College Teaching'], 
			['code' => '140411', 'description' => 'Sports Science (Sports Officiating/Coaching)'], 
			['code' => '140412', 'description' => 'Economics Education'], 
			['code' => '140413', 'description' => 'Bilingual Education'], 
			['code' => '140414', 'description' => 'Filipino Education'], 
			['code' => '140415', 'description' => 'General Science Education'], 
			['code' => '140416', 'description' => 'Health Education'], 
			['code' => '140417', 'description' => 'Home Economics Education'], 
			['code' => '140418', 'description' => 'Language Education/Language Teaching'], 
			['code' => '140419', 'description' => 'Music Education'], 
			['code' => '140420', 'description' => 'Art Education'], 
			['code' => '140421', 'description' => 'Reading Education'], 
			['code' => '140422', 'description' => 'Computer Education (teaching Computer Science)'], 
			['code' => '140423', 'description' => 'Science Education (teaching Science)'], 
			['code' => '140424', 'description' => 'Social Studies Education'], 
			['code' => '140425', 'description' => 'Spanish Education (teaching Spanish)'], 
			['code' => '140426', 'description' => 'Teaching Behavioral Science'], 
			['code' => '140427', 'description' => 'Communication Arts (Pilipino, English)'], 
			['code' => '140429', 'description' => 'Science and Health Education'], 
			['code' => '140431', 'description' => 'Physical Science Education'], 
			['code' => '140432', 'description' => 'Social Science Education'], 
			['code' => '140801', 'description' => 'Industrial Education'], 
			['code' => '140802', 'description' => 'Industrial Arts'], 
			['code' => '140804', 'description' => 'Practical Arts Education'], 
			['code' => '140805', 'description' => 'Vocational/Technical Education'], 
			['code' => '140806', 'description' => 'Technician Teacher Education'], 
			['code' => '140807', 'description' => 'Teaching Elementary Agriculture'], 
			['code' => '140808', 'description' => 'Non-Formal Education'], 
			['code' => '141201', 'description' => 'Childhood Education'], 
			['code' => '141202', 'description' => 'Early Childhood Education'], 
			['code' => '141203', 'description' => 'Kindergarten Education'], 
			['code' => '141601', 'description' => 'Adult Education'], 
			['code' => '142201', 'description' => 'Special Education'], 
			['code' => '142202', 'description' => 'Teaching Handicapped Children'], 
			['code' => '142203', 'description' => 'Applied Deaf Studies'], 
			['code' => '145001', 'description' => 'Educational Administration/Management'], 
			['code' => '145002', 'description' => 'Vocational School Administration/Management'], 
			['code' => '145003', 'description' => 'Educational Programs Management'], 
			['code' => '145004', 'description' => 'School Principalship'], 
			['code' => '145005', 'description' => 'Human Resource Administration'], 
			['code' => '147201', 'description' => 'Guidance and Counselling'], 
			['code' => '147202', 'description' => 'Measurement and Evaluation'], 
			['code' => '147203', 'description' => 'Research and Evaluation'], 
			['code' => '147204', 'description' => 'Curriculum and Instruction'], 
			['code' => '147205', 'description' => 'Educational Guidance and Family Education'], 
			['code' => '147206', 'description' => 'Educational Psychology'], 
			['code' => '147207', 'description' => 'Educational Technology'], 
			['code' => '147208', 'description' => 'Library Science Education'], 
			['code' => '149901', 'description' => 'Agricultural Development Education'], 
			['code' => '149902', 'description' => 'Agricultural Education'], 
			['code' => '149903', 'description' => 'Agricultural Extension Education'], 
			['code' => '149904', 'description' => 'Agricultural Homemaking Education'], 
			['code' => '149905', 'description' => 'Business Education'], 
			['code' => '149906', 'description' => 'Commercial Education'], 
			['code' => '149907', 'description' => 'Extension Education'], 
			['code' => '149908', 'description' => 'Fisheries Education'], 
			['code' => '149909', 'description' => 'Nursing Education'], 
			['code' => '149910', 'description' => 'Secretarial Education'], 
			['code' => '149911', 'description' => 'Basic Agricultural Education/Elementary Agriculture'], 
			['code' => '149912', 'description' => 'Health Professional Education'], 
			['code' => '149913', 'description' => 'Development Education'], 
			['code' => '149914', 'description' => 'Engineering Education'], 
			['code' => '149915', 'description' => 'Occupational Education'], 
			['code' => '149916', 'description' => 'Human Ecology Education'], 
			['code' => '149917', 'description' => 'Agricultural Technology Education'], 
			['code' => '149918', 'description' => 'Environmental Education'], 
			['code' => '149919', 'description' => 'Maritime Education'], 
			['code' => '149920', 'description' => 'Population Education'], 
			['code' => '149921', 'description' => 'Nutrition and Dietetics Teaching'], 
			['code' => '149922', 'description' => 'History Education'], 
			['code' => '149999', 'description' => 'Other Education Science and Teacher Training'], 
			['code' => '180101', 'description' => 'Fine Arts'], 
			['code' => '180104', 'description' => 'Practical Arts'], 
			['code' => '180201', 'description' => 'Art History'], 
			['code' => '180400', 'description' => 'Drawing and Painting'], 
			['code' => '180800', 'description' => 'Sculpturing'], 
			['code' => '182201', 'description' => 'Music'], 
			['code' => '182203', 'description' => 'Music in Musical Sciences'], 
			['code' => '182204', 'description' => 'Music Liturgy'], 
			['code' => '182205', 'description' => 'Piano/Keyboard'], 
			['code' => '182206', 'description' => 'Strings'], 
			['code' => '182207', 'description' => 'Voice'], 
			['code' => '182208', 'description' => 'Winds and Percussion'], 
			['code' => '182209', 'description' => 'Creative and Performing Arts'], 
			['code' => '182210', 'description' => 'Choral/Orchestral Conducting'], 
			['code' => '182211', 'description' => 'Ethnomusicology'], 
			['code' => '182212', 'description' => 'Musicology'], 
			['code' => '182213', 'description' => 'Composition'], 
			['code' => '183201', 'description' => 'Speech and Drama'], 
			['code' => '183202', 'description' => 'Speech and Theater Arts'], 
			['code' => '183204', 'description' => 'Theater Arts (Performance; Malikhaing Pagsulat; Technical Theater Mgt.)'], 
			['code' => '183205', 'description' => 'Production Design'], 
			['code' => '185200', 'description' => 'Interior Design'], 
			['code' => '189902', 'description' => 'Fashion Design and Merchandising'], 
			['code' => '189904', 'description' => 'Visual Communication'], 
			['code' => '189905', 'description' => 'Dance'], 
			['code' => '220100', 'description' => 'General Humanities'], 
			['code' => '221101', 'description' => 'Pilipino/Filipino'], 
			['code' => '221102', 'description' => 'English'], 
			['code' => '221103', 'description' => 'Philippine Literature'], 
			['code' => '221107', 'description' => 'English Literature'], 
			['code' => '221108', 'description' => 'Pilipino Literature'], 
			['code' => '221501', 'description' => 'European Languages'], 
			['code' => '221502', 'description' => 'Spanish'], 
			['code' => '221503', 'description' => 'Language and Literature'], 
			['code' => '221504', 'description' => 'Modern Languages'], 
			['code' => '222100', 'description' => '"Dead" Languages and their Literature'], 
			['code' => '223101', 'description' => 'Linguistics'], 
			['code' => '224101', 'description' => 'Comparative Literature'], 
			['code' => '224102', 'description' => 'Literature'], 
			['code' => '225101', 'description' => 'History'], 
			['code' => '225103', 'description' => 'Development Studies'], 
			['code' => '226100', 'description' => 'Archeology'], 
			['code' => '227100', 'description' => 'Philosophy'], 
			['code' => '229900', 'description' => 'Other Humanities'], 
			['code' => '260001', 'description' => 'Arts (Classical/Philosophy)'], 
			['code' => '260002', 'description' => 'Divinity'], 
			['code' => '260004', 'description' => 'Religion/Spiritual Life'], 
			['code' => '260005', 'description' => 'Theology/Theological Studies'], 
			['code' => '260006', 'description' => 'Evangelical Ministry'], 
			['code' => '260009', 'description' => 'Pastoral Ministry'], 
			['code' => '260010', 'description' => 'Comparative Religions'], 
			['code' => '260011', 'description' => 'Religious Formation'], 
			['code' => '260012', 'description' => 'Biblical Studies'], 
			['code' => '260013', 'description' => 'Christian Leadership'], 
			['code' => '300101', 'description' => 'Social Science'], 
			['code' => '300102', 'description' => 'Behavioral Science'], 
			['code' => '300103', 'description' => 'Human Behavior Technology'], 
			['code' => '300104', 'description' => 'Social Studies'], 
			['code' => '300105', 'description' => 'Applied Social Research'], 
			['code' => '301201', 'description' => 'Applied Economics'], 
			['code' => '301202', 'description' => 'Economics'], 
			['code' => '301205', 'description' => 'Business Economics'], 
			['code' => '301206', 'description' => 'Development Economics'], 
			['code' => '301207', 'description' => 'Management Economics'], 
			['code' => '301208', 'description' => 'Economic Research'], 
			['code' => '301209', 'description' => 'Industrial Economics'], 
			['code' => '302201', 'description' => 'Political Science'], 
			['code' => '302202', 'description' => 'Foreign Service'], 
			['code' => '302203', 'description' => 'International Relations'], 
			['code' => '302204', 'description' => 'Political Economy'], 
			['code' => '303201', 'description' => 'Sociology'], 
			['code' => '303202', 'description' => 'Rural Sociology'], 
			['code' => '303203', 'description' => 'Sociology and Anthropology'], 
			['code' => '303204', 'description' => 'Pastoral Sociology'], 
			['code' => '303205', 'description' => 'Applied Sociology'], 
			['code' => '303301', 'description' => 'Demography'], 
			['code' => '303302', 'description' => 'Population Communication'], 
			['code' => '303303', 'description' => 'Population Studies'], 
			['code' => '304200', 'description' => 'Anthropology'], 
			['code' => '305201', 'description' => 'Psychology'], 
			['code' => '305202', 'description' => 'Industrial Psychology'], 
			['code' => '305204', 'description' => 'Counseling Psychology'], 
			['code' => '305205', 'description' => 'Applied Psychology'], 
			['code' => '305206', 'description' => 'Clinical Psychology'], 
			['code' => '306201', 'description' => 'Geography'], 
			['code' => '306202', 'description' => 'Economic Geography'], 
			['code' => '306203', 'description' => 'Physical Geography'], 
			['code' => '307201', 'description' => 'Islamic Studies'], 
			['code' => '307202', 'description' => 'Philippine Studies/Arts'], 
			['code' => '307203', 'description' => 'Asian Studies/Asian Culture'], 
			['code' => '307204', 'description' => 'International Studies'], 
			['code' => '307205', 'description' => 'Interdisciplinary Studies'], 
			['code' => '307207', 'description' => 'Oriental Religion and Culture'], 
			['code' => '307208', 'description' => 'Regional Studies'], 
			['code' => '307209', 'description' => 'Philippine Muslim Personal Laws'], 
			['code' => '307210', 'description' => 'Folklore'], 
			['code' => '307211', 'description' => 'Southeast Asian Studies'], 
			['code' => '307212', 'description' => 'Culture Heritage Studies'], 
			['code' => '309900', 'description' => 'Other Social and Behavioral Science'], 
			['code' => '309900', 'description' => 'Business Administration'], 
			['code' => '340102', 'description' => 'Commercial Science/Arts'], 
			['code' => '340104', 'description' => 'Business Management'], 
			['code' => '340106', 'description' => 'Entrepreneurial Management'], 
			['code' => '340107', 'description' => 'Commerce'], 
			['code' => '340108', 'description' => 'Administration'], 
			['code' => '340113', 'description' => 'Management'], 
			['code' => '340401', 'description' => 'Secretarial/Medical Secretarial/Clerical'], 
			['code' => '340402', 'description' => 'Office Administration/Management'], 
			['code' => '340404', 'description' => 'Secretarial Administration/Management'], 
			['code' => '340406', 'description' => 'Secretarial Science'], 
			['code' => '340407', 'description' => 'Computer Secretarial'], 
			['code' => '342601', 'description' => 'Business Data Processing'], 
			['code' => '342602', 'description' => 'Data Processing'], 
			['code' => '343201', 'description' => 'Accountancy'], 
			['code' => '343205', 'description' => 'Accountancy and Bookkeeping'], 
			['code' => '343206', 'description' => 'Government Accounting and Auditing'], 
			['code' => '343207', 'description' => 'Business Administration/Management & Accountancy'], 
			['code' => '343401', 'description' => 'Marketing'], 
			['code' => '343402', 'description' => 'Advertising'], 
			['code' => '343601', 'description' => 'Banking and Finance'], 
			['code' => '343602', 'description' => 'Real Estate'], 
			['code' => '343603', 'description' => 'Computational Finance'], 
			['code' => '343901', 'description' => 'Distributive Arts'], 
			['code' => '343902', 'description' => 'Agri-Business'], 
			['code' => '343903', 'description' => 'Agri-Business Management/Administration'], 
			['code' => '343904', 'description' => 'Labor-Management Relations'], 
			['code' => '343905', 'description' => 'Business Technology/Engineering'], 
			['code' => '343906', 'description' => 'Economics and Cooperatives'], 
			['code' => '343907', 'description' => 'Fishery Business Management'], 
			['code' => '343908', 'description' => 'Industrial Management'], 
			['code' => '343911', 'description' => 'International Trade Management'], 
			['code' => '343912', 'description' => 'Transportation Management'], 
			['code' => '343913', 'description' => 'Labor Policy and Administration'], 
			['code' => '343914', 'description' => 'Industrial Relations'], 
			['code' => '343915', 'description' => 'Construction Mangement'], 
			['code' => '343916', 'description' => 'Legal Management'], 
			['code' => '343917', 'description' => 'Livelihood Management'], 
			['code' => '343919', 'description' => 'Home Arts Entrepreneurship'], 
			['code' => '343920', 'description' => 'Computer Management'], 
			['code' => '343922', 'description' => 'Export Management'], 
			['code' => '343923', 'description' => 'Commerce in Taxation'], 
			['code' => '343924', 'description' => 'Business Entrepreneurship'], 
			['code' => '343926', 'description' => 'Technology Communications Management'], 
			['code' => '343927', 'description' => 'Technology Management'], 
			['code' => '343928', 'description' => 'Church Administration'], 
			['code' => '343929', 'description' => 'Agroforestry Entrepreneurship'], 
			['code' => '343930', 'description' => 'Communication Management'], 
			['code' => '345201', 'description' => 'Public Administration/Management'], 
			['code' => '345202', 'description' => 'Fiscal Administration/Studies'], 
			['code' => '345203', 'description' => 'Local Government & Regional Development'], 
			['code' => '345204', 'description' => 'Public Policy and Program Administration'], 
			['code' => '345205', 'description' => 'Organization Analysis and Management'], 
			['code' => '345206', 'description' => 'Public Enterprise Management'], 
			['code' => '345207', 'description' => 'Public and Business Administration'], 
			['code' => '346201', 'description' => 'Hotel and Restaurant Management'], 
			['code' => '346202', 'description' => 'Airline Business Administration/Management'], 
			['code' => '346204', 'description' => 'Educational Administration and Supervision'], 
			['code' => '346205', 'description' => 'Food Service Administration'], 
			['code' => '346206', 'description' => 'Hospital Administration'], 
			['code' => '346209', 'description' => 'Industrial Cafeteria Management'], 
			['code' => '346210', 'description' => 'Institutional Food Administration'], 
			['code' => '346211', 'description' => 'Postal Administration'], 
			['code' => '346212', 'description' => 'Shipping Management and Accountancy'], 
			['code' => '346213', 'description' => 'Small Industry Management'], 
			['code' => '346214', 'description' => 'Media Management'], 
			['code' => '346215', 'description' => 'Police Management'], 
			['code' => '346216', 'description' => 'Vocational School Management'], 
			['code' => '346217', 'description' => 'School Administration/Management'], 
			['code' => '346218', 'description' => 'Agricultural School Administration'], 
			['code' => '346219', 'description' => 'Elementary School Management'], 
			['code' => '346220', 'description' => 'Institutional Development Management'], 
			['code' => '346221', 'description' => 'Nursing Administration/Management'], 
			['code' => '346222', 'description' => 'Customs Administration'], 
			['code' => '347201', 'description' => 'Cooperative Management'], 
			['code' => '347203', 'description' => 'Recreation and Parks Administration'], 
			['code' => '347204', 'description' => 'Supply Administration/Management'], 
			['code' => '347206', 'description' => 'Extension Administration'], 
			['code' => '347207', 'description' => 'Resource Management'], 
			['code' => '347208', 'description' => 'Development Management/Administration'], 
			['code' => '347209', 'description' => 'Administration and Supervision'], 
			['code' => '347210', 'description' => 'Organizational Development and Planning'], 
			['code' => '347212', 'description' => 'Maritime Management'], 
			['code' => '347213', 'description' => 'Developmental Administration/Management'], 
			['code' => '347214', 'description' => 'Livelihood Management'], 
			['code' => '380101', 'description' => 'Laws'], 
			['code' => '380102', 'description' => 'Jurisprudence'], 
			['code' => '380201', 'description' => 'Civil Laws'], 
			['code' => '380400', 'description' => 'International Law'], 
			['code' => '380600', 'description' => 'Labor Law'], 
			['code' => '380800', 'description' => 'Maritime Law'], 
			['code' => '389901', 'description' => 'Laws in Taxation'], 
			['code' => '389902', 'description' => 'Criminal Justice'], 
			['code' => '389903', 'description' => 'Economic Law'], 
			['code' => '420201', 'description' => 'Biological Science'], 
			['code' => '420202', 'description' => 'Biology'], 
			['code' => '420203', 'description' => 'Bio-Chemistry'], 
			['code' => '420204', 'description' => 'Botany'], 
			['code' => '420205', 'description' => 'Entomology'], 
			['code' => '420206', 'description' => 'Human Biology'], 
			['code' => '420207', 'description' => 'Marine Biology'], 
			['code' => '420208', 'description' => 'Microbiology'], 
			['code' => '420209', 'description' => 'Pharmacology'], 
			['code' => '420210', 'description' => 'Physiology'], 
			['code' => '420212', 'description' => 'Zoology'], 
			['code' => '420213', 'description' => 'Applied Biology'], 
			['code' => '420214', 'description' => 'Biotechnology'], 
			['code' => '420215', 'description' => 'Molecular Biology and Biotechnology'], 
			['code' => '420216', 'description' => 'Applied Zoology'], 
			['code' => '420217', 'description' => 'Genetics'], 
			['code' => '421201', 'description' => 'Chemical Research'], 
			['code' => '421202', 'description' => 'Chemical Technology'], 
			['code' => '421203', 'description' => 'Chemistry'], 
			['code' => '421204', 'description' => 'Industrial Chemistry'], 
			['code' => '422201', 'description' => 'Geology'], 
			['code' => '422202', 'description' => 'Volcanology'], 
			['code' => '422203', 'description' => 'Geological Techniques'], 
			['code' => '422204', 'description' => 'Marine Geology'], 
			['code' => '423201', 'description' => 'Applied Physics'], 
			['code' => '423202', 'description' => 'Metallurgy'], 
			['code' => '423203', 'description' => 'Physics'], 
			['code' => '423204', 'description' => 'Physics-Mathematics'], 
			['code' => '424200', 'description' => 'Astronomy'], 
			['code' => '425200', 'description' => 'Meteorology'], 
			['code' => '426201', 'description' => 'Marine Science'], 
			['code' => '426202', 'description' => 'Oceanography'], 
			['code' => '426203', 'description' => 'Marine Physical Science'], 
			['code' => '426204', 'description' => 'Marine Bio-Diversity'], 
			['code' => '429901', 'description' => 'General Science'], 
			['code' => '429902', 'description' => 'Natural Science'], 
			['code' => '429904', 'description' => 'Applied Science'], 
			['code' => '460100', 'description' => 'General Mathematics'], 
			['code' => '461101', 'description' => 'Applied Statistics'], 
			['code' => '461102', 'description' => 'Experimental Statistics'], 
			['code' => '461103', 'description' => 'Statistics'], 
			['code' => '461104', 'description' => 'Operations Research'], 
			['code' => '462100', 'description' => 'Actuarial Science'], 
			['code' => '463901', 'description' => 'Applied Mathematics'], 
			['code' => '463902', 'description' => 'Mathematical Science'], 
			['code' => '463903', 'description' => 'Actuarial Mathematics'], 
			['code' => '464101', 'description' => 'Computer Science'], 
			['code' => '464102', 'description' => 'Computer Data Processing Management'], 
			['code' => '464104', 'description' => 'Computer Technology'], 
			['code' => '464105', 'description' => 'Information and Computer Science'], 
			['code' => '464106', 'description' => 'Computer Applications'], 
			['code' => '464107', 'description' => 'Information Management'], 
			['code' => '464108', 'description' => 'Information Technology'], 
			['code' => '500201', 'description' => 'Sanitary Science'], 
			['code' => '500202', 'description' => 'Community Health'], 
			['code' => '500203', 'description' => 'Public Health/Medical Health'], 
			['code' => '500205', 'description' => 'Health and Social Science'], 
			['code' => '500206', 'description' => 'Community Health Development and Management'], 
			['code' => '500207', 'description' => 'Cosmetic Science'], 
			['code' => '500601', 'description' => 'Medicine'], 
			['code' => '500602', 'description' => 'Anesthesiology'], 
			['code' => '500603', 'description' => 'Internal Medicine'], 
			['code' => '500604', 'description' => 'Clinical Medicine (Epidemiology, Surgery)'], 
			['code' => '500801', 'description' => 'Occupational Therapy/Health'], 
			['code' => '500802', 'description' => 'Physical Therapy'], 
			['code' => '500803', 'description' => 'Speech Pathology'], 
			['code' => '500804', 'description' => 'Respiratory/Pulmunary Therapy'], 
			['code' => '500805', 'description' => 'Human Kinetics'], 
			['code' => '500806', 'description' => 'Physio-Therapy'], 
			['code' => '500807', 'description' => 'Rehabilitation Science'], 
			['code' => '501200', 'description' => 'Nursing'], 
			['code' => '501500', 'description' => 'Midwifery'], 
			['code' => '501701', 'description' => 'Radiologic Technology'], 
			['code' => '503001', 'description' => 'Medical Technology'], 
			['code' => '503002', 'description' => 'Medical Microbiology'], 
			['code' => '504201', 'description' => 'Dental Medicine'], 
			['code' => '504202', 'description' => 'Dental Public Work'], 
			['code' => '504203', 'description' => 'Orthondontics'], 
			['code' => '505201', 'description' => 'Industrial Pharmacy'], 
			['code' => '505202', 'description' => 'Pharmaceutical Chemistry'], 
			['code' => '505203', 'description' => 'Pharmacy'], 
			['code' => '505204', 'description' => 'Hospital Pharmacy'], 
			['code' => '506200', 'description' => 'Optometry'], 
			['code' => '506201', 'description' => 'Clinical Audiology'], 
			['code' => '507200', 'description' => 'Nutrition and Dietetics'], 
			['code' => '509901', 'description' => 'Rural Medicine'], 
			['code' => '509902', 'description' => 'Paramedics'], 
			['code' => '509903', 'description' => 'Health Science Education (15 May 2000 for Asso in HSE program)'], 
			['code' => '520000', 'description' => 'Technical/Vocational'], 
			['code' => '527601', 'description' => 'Garment Technology'], 
			['code' => '527602', 'description' => 'Clothing Technology'], 
			['code' => '527603', 'description' => 'Trade Technology'], 
			['code' => '540301', 'description' => 'Basic Engineering'], 
			['code' => '540401', 'description' => 'Aeronautical Engineering'], 
			['code' => '540402', 'description' => 'Aerospace Engineering'], 
			['code' => '540403', 'description' => 'Aviation Electronics/Electrical Engineering'], 
			['code' => '540404', 'description' => 'Avionics Engineering/Technology/Civil Aviation'], 
			['code' => '540405', 'description' => 'Air Transportation'], 
			['code' => '540406', 'description' => 'Aircraft Maintenance Technology'], 
			['code' => '540407', 'description' => 'Aircraft/Avionics Technology'], 
			['code' => '541201', 'description' => 'Ceramics Engineering'], 
			['code' => '541202', 'description' => 'Chemical Engineering'], 
			['code' => '541203', 'description' => 'Chemical Engineering Technology'], 
			['code' => '541204', 'description' => 'Textile Engineering'], 
			['code' => '541205', 'description' => 'Biochemical Engineering'], 
			['code' => '541601', 'description' => 'Civil Engineering'], 
			['code' => '541602', 'description' => 'Construction Technology'], 
			['code' => '541603', 'description' => 'Building Technology'], 
			['code' => '541604', 'description' => 'Structural Engineering'], 
			['code' => '541801', 'description' => 'Geodetic Engineering'], 
			['code' => '541802', 'description' => 'Mineral Land Surveying'], 
			['code' => '542201', 'description' => 'Radio and Electronics Engineering'], 
			['code' => '542202', 'description' => 'Computer Engineering'], 
			['code' => '542203', 'description' => 'Electrical Engineering'], 
			['code' => '542205', 'description' => 'Electrical Technology'], 
			['code' => '542206', 'description' => 'Electronics Engineering/Technology'], 
			['code' => '542207', 'description' => 'Electronics and Communications Engineering'], 
			['code' => '542209', 'description' => 'Radio Communication Technology'], 
			['code' => '542210', 'description' => 'Applied Electrical Science'], 
			['code' => '542211', 'description' => 'Software Engineering/Technology'], 
			['code' => '542212', 'description' => 'Instrumentation and Control Technology'], 
			['code' => '542213', 'description' => 'Remote Sensing'], 
			['code' => '542601', 'description' => 'Industrial Design'], 
			['code' => '542602', 'description' => 'Industrial and Management Engineering'], 
			['code' => '542604', 'description' => 'Industrial Engineering'], 
			['code' => '542605', 'description' => 'Industrial Technology'], 
			['code' => '542606', 'description' => 'Management Engineering'], 
			['code' => '542607', 'description' => 'Manufacturing/Production Engineering'], 
			['code' => '542608', 'description' => 'Industrial Development and Technology'], 
			['code' => '543200', 'description' => 'Metallurgical Engineering'], 
			['code' => '543601', 'description' => 'Mining Engineering'], 
			['code' => '543602', 'description' => 'Mineral Processing Technology'], 
			['code' => '543603', 'description' => 'Mining Technology'], 
			['code' => '544205', 'description' => 'Mechanical Engineering'], 
			['code' => '544206', 'description' => 'Mechanical Technology'], 
			['code' => '544208', 'description' => 'Automotive Technology'], 
			['code' => '544209', 'description' => 'Geothermal Engineering'], 
			['code' => '545001', 'description' => 'Environmental and Sanitary Engineering'], 
			['code' => '545002', 'description' => 'Sanitary Engineering'], 
			['code' => '545003', 'description' => 'Public Health Engineering'], 
			['code' => '545300', 'description' => 'Agricultural Engineering'], 
			['code' => '546301', 'description' => 'Forest Products Engineering'], 
			['code' => '549901', 'description' => 'Engineering Technology'], 
			['code' => '549903', 'description' => 'Plumbing Engineering'], 
			['code' => '549904', 'description' => 'Energy Engineering'], 
			['code' => '549907', 'description' => 'Food Engineering'], 
			['code' => '549908', 'description' => 'Water Resources Engineering'], 
			['code' => '549909', 'description' => 'Materials Science and Engineering'], 
			['code' => '549911', 'description' => 'Genetics Engineering'], 
			['code' => '549912', 'description' => 'Transport Engineering'], 
			['code' => '549913', 'description' => 'Nuclear Engineering'], 
			['code' => '549915', 'description' => 'Engineering Design'], 
			['code' => '549916', 'description' => 'Meteorological Engineering'], 
			['code' => '549919', 'description' => 'Technology/Engineering'], 
			['code' => '549921', 'description' => 'Petroleum Engineering'], 
			['code' => '549922', 'description' => 'Marine Engineering/Technology'], 
			['code' => '549923', 'description' => 'Naval Architecture and Marine Engineering'], 
			['code' => '580101', 'description' => 'Architecture'], 
			['code' => '580102', 'description' => 'Architectural Drafting'], 
			['code' => '580103', 'description' => 'Architectural Science/Technology'], 
			['code' => '580200', 'description' => 'Architectural Design'], 
			['code' => '581201', 'description' => 'Landscape Architecture'], 
			['code' => '581202', 'description' => 'Tropical Landscape Architecture'], 
			['code' => '582201', 'description' => 'Town and Country Planning'], 
			['code' => '582202', 'description' => 'Urban and Regional Planning'], 
			['code' => '582203', 'description' => 'Community Architecture'], 
			['code' => '582204', 'description' => 'Land Use Planning'], 
			['code' => '582205', 'description' => 'Transportation Planning'], 
			['code' => '582206', 'description' => 'Estate Planning Development'], 
			['code' => '582207', 'description' => 'Public Works Planning and Development'], 
			['code' => '620101', 'description' => 'Agricultural Technology'], 
			['code' => '620102', 'description' => 'Agricultural Science'], 
			['code' => '620103', 'description' => 'Agriculture'], 
			['code' => '620301', 'description' => 'Animal Husbandry'], 
			['code' => '620302', 'description' => 'Animal Science'], 
			['code' => '620303', 'description' => 'Animal Technology'], 
			['code' => '620601', 'description' => 'Horticulture'], 
			['code' => '620602', 'description' => 'Plant Pathology'], 
			['code' => '620603', 'description' => 'Plant Science'], 
			['code' => '620604', 'description' => 'Horticulture Management'], 
			['code' => '620605', 'description' => 'Plant Genetic Resources Conservation and Management'], 
			['code' => '620801', 'description' => 'Agronomy'], 
			['code' => '620802', 'description' => 'Plant Breeding'], 
			['code' => '620803', 'description' => 'Seed Science'], 
			['code' => '620804', 'description' => 'Weed Science'], 
			['code' => '620805', 'description' => 'Grain Science'], 
			['code' => '620806', 'description' => 'Crop Science'], 
			['code' => '620807', 'description' => 'Crop Protection'], 
			['code' => '621200', 'description' => 'Agricultural Economics'], 
			['code' => '622201', 'description' => 'Food Technology'], 
			['code' => '622203', 'description' => 'Food Science'], 
			['code' => '622204', 'description' => 'Food Science and Technology'], 
			['code' => '622205', 'description' => 'Food Processing'], 
			['code' => '622601', 'description' => 'Soil Science'], 
			['code' => '622602', 'description' => 'Soils/Water Development'], 
			['code' => '622603', 'description' => 'Soil Conservation and Management'], 
			['code' => '623201', 'description' => 'Veterinary Medicine'], 
			['code' => '623202', 'description' => 'Veterinary Parasitology'], 
			['code' => '623203', 'description' => 'Veterinary Pathology'], 
			['code' => '623204', 'description' => 'Veterinary Technology'], 
			['code' => '624902', 'description' => 'Agricultural Chemistry'], 
			['code' => '624903', 'description' => 'Agricultural Development'], 
			['code' => '624904', 'description' => 'Agricultural Extension'], 
			['code' => '624905', 'description' => 'Agricultural Homemaking'], 
			['code' => '624906', 'description' => 'Agricultural Management'], 
			['code' => '624907', 'description' => 'Development Communication'], 
			['code' => '624908', 'description' => 'Agricultural Technology Management'], 
			['code' => '624909', 'description' => 'Agrometeorology'], 
			['code' => '624911', 'description' => 'Farming System'], 
			['code' => '624912', 'description' => 'Sugar Technology'], 
			['code' => '624913', 'description' => 'Rice Technology'], 
			['code' => '624915', 'description' => 'Agrarian Studies/Reform'], 
			['code' => '624918', 'description' => 'Agro-Industrial Technology Mgt.'], 
			['code' => '624919', 'description' => 'Sericulture'], 
			['code' => '626201', 'description' => 'Forestry'], 
			['code' => '626202', 'description' => 'Agro-Forestry'], 
			['code' => '626204', 'description' => 'Forest Ranger'], 
			['code' => '626205', 'description' => 'Forest Biological Science'], 
			['code' => '626206', 'description' => 'Forest Entomology'], 
			['code' => '626207', 'description' => 'Forest Resource Management'], 
			['code' => '626208', 'description' => 'Wild Life Studies'], 
			['code' => '626209', 'description' => 'Wood Science and Technology'], 
			['code' => '626210', 'description' => 'Forest Technology'], 
			['code' => '627201', 'description' => 'Fisheries'], 
			['code' => '627202', 'description' => 'Fisheries Technology'], 
			['code' => '627204', 'description' => 'Fishery Farming Extension'], 
			['code' => '627205', 'description' => 'Fishing Technology'], 
			['code' => '627206', 'description' => 'Inland Fisheries'], 
			['code' => '627207', 'description' => 'Aquaculture'], 
			['code' => '627208', 'description' => 'Fish Processing Technology'], 
			['code' => '627209', 'description' => 'Fisheries Biology'], 
			['code' => '627210', 'description' => 'Aquaculture Technology'], 
			['code' => '660101', 'description' => 'Family Life and Child Development'], 
			['code' => '660102', 'description' => 'Home Economics'], 
			['code' => '660103', 'description' => 'Human Ecology'], 
			['code' => '660104', 'description' => 'Family Life'], 
			['code' => '660105', 'description' => 'Family Resource Management'], 
			['code' => '660106', 'description' => 'Early Childhood Development'], 
			['code' => '661201', 'description' => 'Foods and Nutrition'], 
			['code' => '661202', 'description' => 'Community Nutrition'], 
			['code' => '661204', 'description' => 'Nutrition'], 
			['code' => '661206', 'description' => 'Applied Nutrition'], 
			['code' => '661207', 'description' => 'Nutrition and Food Planning'], 
			['code' => '663200', 'description' => 'Home Economics with Emphasis on Household Arts'], 
			['code' => '669901', 'description' => 'Home Extension'], 
			['code' => '669902', 'description' => 'Home Technology'], 
			['code' => '669903', 'description' => 'Homemaking'], 
			['code' => '787201', 'description' => 'Tourism'], 
			['code' => '787203', 'description' => 'Tourism and Travel Management'], 
			['code' => '787204', 'description' => 'Tourism and Hotel & Restaurant Mgt.'], 
			['code' => '840101', 'description' => 'Communication'], 
			['code' => '840102', 'description' => 'Speech Communication'], 
			['code' => '840103', 'description' => 'Writing'], 
			['code' => '840201', 'description' => 'Business Journalism'], 
			['code' => '840202', 'description' => 'Journalism'], 
			['code' => '840203', 'description' => 'Literature in Journalism'], 
			['code' => '840401', 'description' => 'Broadcast Communication'], 
			['code' => '840402', 'description' => 'Broadcast'], 
			['code' => '840700', 'description' => 'Public Relations and Media Management'], 
			['code' => '840901', 'description' => 'Mass Communication'], 
			['code' => '840908', 'description' => 'Communication Research'], 
			['code' => '840909', 'description' => 'Film and Audio Visual Communication'], 
			['code' => '840910', 'description' => 'Maikling Pagsulat'], 
			['code' => '840911', 'description' => 'Organizational Communication'], 
			['code' => '840912', 'description' => 'Christian Communication'], 
			['code' => '842201', 'description' => 'Library and Information Science'], 
			['code' => '842202', 'description' => 'Library Science'], 
			['code' => '891301', 'description' => 'Criminology'], 
			['code' => '891303', 'description' => 'Criminology and Police Administration'], 
			['code' => '891900', 'description' => 'Other Civil Security and Military'], 
			['code' => '893201', 'description' => 'Social Services'], 
			['code' => '893202', 'description' => 'Social Work'], 
			['code' => '893203', 'description' => 'Social Development'], 
			['code' => '893301', 'description' => 'Community Development'], 
			['code' => '893302', 'description' => 'Livelihood Management'], 
			['code' => '893303', 'description' => 'Community Organizing'], 
			['code' => '893304', 'description' => 'Extension Service Management'], 
			['code' => '893305', 'description' => 'Rural Development'], 
			['code' => '893306', 'description' => 'Multicultural Community Development'], 
			['code' => '893307', 'description' => 'Participatory Development'], 
			['code' => '895201', 'description' => 'Environment'], 
			['code' => '895202', 'description' => 'Ecology'], 
			['code' => '895203', 'description' => 'Environmental Planning/Management'], 
			['code' => '895204', 'description' => 'Environmental Science'], 
			['code' => '897201', 'description' => 'Marine Transportation'], 
			['code' => '897202', 'description' => 'Nautical Science'], 
			['code' => '898201', 'description' => 'Human Resource Development and Planning'], 
			['code' => '898202', 'description' => 'Personnel and Human Resources Management'], 
			['code' => '899900', 'description' => 'Women Development'], 
			['code' => '899999', 'description' => 'Other Education not elsewhere coded (NEC)']
        ]);
    }
}
