<?php

use Illuminate\Database\Seeder;

class SchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table = DB::table('school');
        $data = $this->getData();
        
        $table->insert($data);

        
        // select concat(substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand()*36+1, 1),
        //       substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand()*36+1, 1),
        //       substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand()*36+1, 1),
        //       substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand()*36+1, 1),
        //       substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand()*36+1, 1),
        //       substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand()*36+1, 1),
        //       substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand()*36+1, 1),
        //       substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand()*36+1, 1)
        //      ) as LicensePlaceNumber;


        //update school set type = 
        //ELT(0.5 + RAND() * 3, 'LUC', 'CHED', 'Private')
    }

    static function getData()
    {
        return [
            ['code' => '30001', 'name' => 'ABE International College of Business & Economics-Cabanatuan City, Inc.'],
            ['code' => '30002', 'name' => 'ABE International College of Business & Accountancy, Inc.-Malolos City'],
            ['code' => '30003', 'name' => 'Academia De San Lorenzo Dema-Ala, Inc.'],
            ['code' => '30004', 'name' => 'ACLC College of Apalit, Inc.'],
            ['code' => '30005', 'name' => 'ACLC College of Balanga, Inc.'],
            ['code' => '30006', 'name' => 'ACLC College of Gapan, Inc.'],
            ['code' => '30007', 'name' => 'ACLC College of Mabalacat, Inc.'],
            ['code' => '30008', 'name' => 'ACLC College of Malolos, Inc.'],
            ['code' => '30009', 'name' => 'ACLC College of Meycauayan, Inc.'],
            ['code' => '30010', 'name' => 'ACLC College of Poblacion, Baliuag, Inc.'],
            ['code' => '30011', 'name' => 'ACLC College of Sta. Maria, Inc.'],
            ['code' => '30012', 'name' => 'AMA Computer College-Angeles City'],
            ['code' => '30013', 'name' => 'AMA Computer College-Cabanatuan City'],
            ['code' => '30014', 'name' => 'AMA Computer College-Malolos City'],
            ['code' => '30015', 'name' => 'AMA Computer College-Olongapo City'],
            ['code' => '30016', 'name' => 'AMA Computer College-San Fernando City'],
            ['code' => '30017', 'name' => 'AMA Computer College-Tarlac City'],
            ['code' => '30018', 'name' => 'Angeles University Foundation'],
            ['code' => '30019', 'name' => 'Asia Pacific College of Advanced Studies'],
            ['code' => '30020', 'name' => 'Asian Institute of Computer Studies-Central Inc.'],
            ['code' => '30021', 'name' => 'Aurora Polytechnic College, Inc.'],
            ['code' => '30022', 'name' => 'Aurora State College of Technology-Casiguran Campus'],
            ['code' => '30023', 'name' => 'Aurora State College of Technology-Main Campus'],
            ['code' => '30024', 'name' => 'Aurora State College of Technology-Maria Aurora Campus'],
            ['code' => '30025', 'name' => 'Baliuag University'],
            ['code' => '30026', 'name' => 'Baliwag Maritime Academy'],
            ['code' => '30027', 'name' => 'Bataan Heroes Memorial College'],
            ['code' => '30028', 'name' => 'Bataan Peninsula State University-Abucay Campus'],
            ['code' => '30029', 'name' => 'Bataan Peninsula State University-Balanga Campus'],
            ['code' => '30030', 'name' => 'Bataan Peninsula State University-Dinalupihan Campus'],
            ['code' => '30031', 'name' => 'Bataan Peninsula State University-Main Campus'],
            ['code' => '30032', 'name' => 'Bataan Peninsula State University-Orani Campus'],
            ['code' => '30033', 'name' => 'Bestlink College of the Philippines, Inc.'],
            ['code' => '30034', 'name' => 'Bulacan Agricultural State College'],
            ['code' => '30035', 'name' => 'Bulacan State University – Bulacan (Meneses) Campus'],
            ['code' => '30036', 'name' => 'Bulacan State University – Bustos Campus'],
            ['code' => '30037', 'name' => 'Bulacan State University – Hagonoy Campus'],
            ['code' => '30038', 'name' => 'Bulacan State University – Main Campus'],
            ['code' => '30039', 'name' => 'Bulacan State University – Sarmiento Campus'],
            ['code' => '30040', 'name' => 'Camiling Colleges'],
            ['code' => '30041', 'name' => 'Carthel Science Educational Foundation (CSEF), Inc.'],
            ['code' => '30042', 'name' => 'Central Luzon College of Science And Technology Olongapo City, Inc.'],
            ['code' => '30043', 'name' => 'Central Luzon College of Science And Technology, Inc.-San Fernando City'],
            ['code' => '30044', 'name' => 'Central Luzon Doctors’ Hospital Educational Institution, Inc.'],
            ['code' => '30045', 'name' => 'Central Luzon State University'],
            ['code' => '30046', 'name' => 'Centro Colegio De Tarlac, Inc.'],
            ['code' => '30047', 'name' => 'Centro Escolar University At Malolos'],
            ['code' => '30048', 'name' => 'CIT Colleges of Paniqui Foundation, Inc.'],
            ['code' => '30049', 'name' => 'Clark College of Science And Technology, Inc.'],
            ['code' => '30050', 'name' => 'Colegio De Calumpit, Inc.'],
            ['code' => '30051', 'name' => 'Colegio De San Gabriel Arcangel, Inc.'],
            ['code' => '30052', 'name' => 'Colegio De San Juan De Letran'],
            ['code' => '30053', 'name' => 'Colegio De San Pascual Baylon'],
            ['code' => '30054', 'name' => 'Colegio De Sebastian-Pampanga, Inc.'],
            ['code' => '30055', 'name' => 'College For Research & Technology of Cabanatuan, Inc.'],
            ['code' => '30056', 'name' => 'College of Mary Immaculate of Pandi, Bulacan, Inc.'],
            ['code' => '30057', 'name' => 'College of Our Lady of Mt. Carmel (Pampanga), Inc.'],
            ['code' => '30058', 'name' => 'College of Saint Lawrence, Inc.'],
            ['code' => '30059', 'name' => 'College of Subic Montessori Subic Bay, Inc.'],
            ['code' => '30060', 'name' => 'College of Subic Montessori, Inc.'],
            ['code' => '30061', 'name' => 'College of the Holy Spirit of Tarlac'],
            ['code' => '30062', 'name' => 'College of the Immaculate Conception'],
            ['code' => '30063', 'name' => 'College of the Most Holy Trinity Catholic Foundation, Inc.'],
            ['code' => '30064', 'name' => 'College of the Our Lady of Mercy of Pulilan Foundation, Inc.'],
            ['code' => '30065', 'name' => 'Colleges of Advance Technology And Management of the Phils. (CATMAN), Inc.'],
            ['code' => '30066', 'name' => 'Columban College, Inc.-Olongapo City'],
            ['code' => '30067', 'name' => 'Columban College-Sta. Cruz'],
            ['code' => '30068', 'name' => 'Comteq Computer & Business College'],
            ['code' => '30069', 'name' => 'Concepcion Holy Cross College, Inc.'],
            ['code' => '30070', 'name' => 'Core Gateway College, Inc.'],
            ['code' => '30071', 'name' => 'Divina Pastora College'],
            ['code' => '30072', 'name' => 'Dominican College of Tarlac, Inc.'],
            ['code' => '30073', 'name' => 'Don Honorio Ventura Technological State University – Main'],
            ['code' => '30074', 'name' => 'Dr. Gloria D. Lacson Foundation Colleges of Cabanatuan City, Inc.'],
            ['code' => '30075', 'name' => 'Dr. Gloria D. Lacson Foundation Colleges, Inc.'],
            ['code' => '30076', 'name' => 'Dr. Yanga’s Colleges, Inc.'],
            ['code' => '30077', 'name' => 'Eastwoods Professional College of Science And Technology, Inc.'],
            ['code' => '30078', 'name' => 'Ecumenical Christian College, Inc.'],
            ['code' => '30079', 'name' => 'Emmanuel System College of Bulacan, Inc.'],
            ['code' => '30080', 'name' => 'Erhard Science College-Bulacan, Inc.'],
            ['code' => '30081', 'name' => 'Exact Colleges of Asia, Inc.'],
            ['code' => '30082', 'name' => 'Fernandez College of Arts & Technology'],
            ['code' => '30083', 'name' => 'First City Providential College, Inc.'],
            ['code' => '30084', 'name' => 'Fundamental Baptist College For Asians, Inc.'],
            ['code' => '30085', 'name' => 'General De Jesus College'],
            ['code' => '30086', 'name' => 'Gerona Junior Colege, Inc.'],
            ['code' => '30087', 'name' => 'Golden Valley Colleges, Inc.'],
            ['code' => '30088', 'name' => 'Guagua National Colleges'],
            ['code' => '30089', 'name' => 'Holy Angel University, Inc.'],
            ['code' => '30090', 'name' => 'Holy Cross College-Nueva Ecija'],
            ['code' => '30091', 'name' => 'Holy Cross College-Pampanga'],
            ['code' => '30092', 'name' => 'Holy Rosary Colleges Foundation of Calaba'],
            ['code' => '30093', 'name' => 'Immaculate Conception I-College of Arts And Technology, Inc.'],
            ['code' => '30094', 'name' => 'Immaculate Conception Major Seminary'],
            ['code' => '30095', 'name' => 'Interworld College of Science And Technology – Tarlac City'],
            ['code' => '30096', 'name' => 'Interworld Colleges Foundation, Inc. – Paniqui Tarlac'],
            ['code' => '30097', 'name' => 'Jesus Is Lord College Foundation, Inc.'],
            ['code' => '30098', 'name' => 'Jocson College, Inc.'],
            ['code' => '30099', 'name' => 'Jose C. Feliciano College Foundation, Inc.'],
            ['code' => '30100', 'name' => 'La Concepcion College'],
            ['code' => '30101', 'name' => 'La Consolacion University Philippines (Formerly University of Regina Carmeli)'],
            ['code' => '30102', 'name' => 'La Fortuna College'],
            ['code' => '30103', 'name' => 'La Verdad Christian College, Inc.'],
            ['code' => '30104', 'name' => 'Liceo De Pulilan Colleges, Inc.'],
            ['code' => '30105', 'name' => 'Lourdes College of Bulacan, Inc.'],
            ['code' => '30106', 'name' => 'Lourdes College Of Pampanga, Inc.'],
            ['code' => '30107', 'name' => 'Lyceum of Subic Bay, Inc.'],
            ['code' => '30108', 'name' => 'Lyceum of the East-Aurora, Inc.'],
            ['code' => '30109', 'name' => 'M. V. Gallego Foundation Colleges'],
            ['code' => '30110', 'name' => 'Magsaysay Memorial College of Zambales, Inc.'],
            ['code' => '30111', 'name' => 'Maria Assumpta Seminary'],
            ['code' => '30112', 'name' => 'Marian College of Baliuag, Inc.'],
            ['code' => '30113', 'name' => 'Maritime Academy of Asia And the Pacific'],
            ['code' => '30114', 'name' => 'Mary the Queen College (Pampanga), Inc.'],
            ['code' => '30115', 'name' => 'Mater Redemptoris College of San Jose City, Inc.'],
            ['code' => '30116', 'name' => 'Megabyte College, Inc.-Florida Blanca'],
            ['code' => '30117', 'name' => 'Metro Subic Colleges, Inc.'],
            ['code' => '30118', 'name' => 'Meycauayan College'],
            ['code' => '30119', 'name' => 'Micro Asia College of Science & Technology, Inc.'],
            ['code' => '30120', 'name' => 'Microcity Computer of Business And Technology( Formerly: Microcity Computer College Foundation, Inc.)'],
            ['code' => '30121', 'name' => 'Midway Maritime Foundation, Inc.'],
            ['code' => '30122', 'name' => 'Mondriaan Aura College'],
            ['code' => '30123', 'name' => 'Mother of Good Counsel Seminary'],
            ['code' => '30124', 'name' => 'Mount Carmel College of Baler, Inc.'],
            ['code' => '30125', 'name' => 'Mount Carmel College of Casiguran, Inc.'],
            ['code' => '30126', 'name' => 'Mt. Carmel College of Bocaue Bulacan, Inc.'],
            ['code' => '30127', 'name' => 'Nazarenus College And Hospital Foundation, Inc.'],
            ['code' => '30128', 'name' => 'New Era University'],
            ['code' => '30129', 'name' => 'Northern Zambales College, Inc.'],
            ['code' => '30130', 'name' => 'Nueva Ecija Doctors Colleges, Inc.'],
            ['code' => '30131', 'name' => 'Nueva Ecija University of Science And Technology – Gabaldon Campus'],
            ['code' => '30132', 'name' => 'Nueva Ecija University of Science And Technology-Atate Campus'],
            ['code' => '30133', 'name' => 'Nueva Ecija University of Science And Technology-Carranglan Campus'],
            ['code' => '30134', 'name' => 'Nueva Ecija University of Science And Technology-Fort Magsaysay Campus'],
            ['code' => '30135', 'name' => 'Nueva Ecija University of Science And Technology-Gen. Tinio Campus'],
            ['code' => '30136', 'name' => 'Nueva Ecija University of Science and Technology-San Isidro Campus'],
            ['code' => '30137', 'name' => 'Nueva Ecija University of Science And Technology-Sumacab Campus'],
            ['code' => '30138', 'name' => 'Osias Colleges, Inc.'],
            ['code' => '30139', 'name' => 'Our Lady of Fatima University – Pampanga, Inc.'],
            ['code' => '30140', 'name' => 'Our Lady of Fatima University, Inc (Formerly East Central Colleges)'],
            ['code' => '30141', 'name' => 'Our Lady of Manaoag Montessori College, Inc.'],
            ['code' => '30142', 'name' => 'Our Lady of Peace College Seminary'],
            ['code' => '30143', 'name' => 'Our Lady of the Sacred Heart College of Guimba, Inc.'],
            ['code' => '30144', 'name' => 'Pamantasan Ng Araullo (Araullo University), Inc.'],
            ['code' => '30145', 'name' => 'Pampanga Colleges, Inc.'],
            ['code' => '30146', 'name' => 'Pampanga State Agricultural University ( Formerly: Pampanga Agricultural College)'],
            ['code' => '30147', 'name' => 'Philippine Merchant Marine Academy'],
            ['code' => '30148', 'name' => 'Philippine Rehabilitation Institute Foundation, Inc.'],
            ['code' => '30149', 'name' => 'Philippine Women’s University Career Development And Continuing Education Center Bataan, Inc.'],
            ['code' => '30150', 'name' => 'Philippine Women’s University Career Development And Continuing Education Center Tarlac, Inc.'],
            ['code' => '30151', 'name' => 'Ramon Magsaysay Technological University (Botolan Campus)'],
            ['code' => '30152', 'name' => 'Ramon Magsaysay Technological University (Main Campus)'],
            ['code' => '30153', 'name' => 'Ramon Magsaysay Technological University (San Marcelino Campus)'],
            ['code' => '30154', 'name' => 'Richwell Colleges, Inc.'],
            ['code' => '30155', 'name' => 'RCC Colegio De San Rafael, Inc.'],
            ['code' => '30156', 'name' => 'Republic Central Colleges'],
            ['code' => '30157', 'name' => 'Sact St. Mutien College, Inc.'],
            ['code' => '30158', 'name' => 'Saint Mary’s Angels College of Pampanga, Inc.'],
            ['code' => '30159', 'name' => 'San Jose Christian Colleges'],
            ['code' => '30160', 'name' => 'Santa Rita College of Pampanga, Inc.'],
            ['code' => '30161', 'name' => 'Siena College of San Jose, Inc.'],
            ['code' => '30162', 'name' => 'SJDM Cornerstone College, Inc.'],
            ['code' => '30163', 'name' => 'Somascan Fathers Seminary'],
            ['code' => '30164', 'name' => 'St. Anthony College of Technology'],
            ['code' => '30165', 'name' => 'St. Augustine Colleges Foundation, Inc.'],
            ['code' => '30166', 'name' => 'St. Benilde Center For Global Competence, Inc.'],
            ['code' => '30167', 'name' => 'St. Elizabeth Global Skills Institute, Inc.'],
            ['code' => '30168', 'name' => 'St. Joseph College of Bulacan, Inc.'],
            ['code' => '30169', 'name' => 'St. Joseph College-Olongapo Inc.'],
            ['code' => '30170', 'name' => 'St. Joseph’s College of Balanga City, Inc.'],
            ['code' => '30171', 'name' => 'St. Mary’s College of Baliuag'],
            ['code' => '30172', 'name' => 'St. Mary’s College of Meycauayan'],
            ['code' => '30173', 'name' => 'St. Nicolas College of Business And Technology, Inc.'],
            ['code' => '30174', 'name' => 'St. Paul College of Arts And Sciences, Inc.'],
            ['code' => '30175', 'name' => 'St. Paul College of Technology'],
            ['code' => '30176', 'name' => 'St. Paul University at San Miguel'],
            ['code' => '30177', 'name' => 'St. Rose College Educational Foundation, Inc.'],
            ['code' => '30178', 'name' => 'St. Thomas More College'],
            ['code' => '30179', 'name' => 'STI College – Angeles'],
            ['code' => '30180', 'name' => 'STI College – Balagtas'],
            ['code' => '30181', 'name' => 'STI College – Baliuag'],
            ['code' => '30182', 'name' => 'STI College – Malolos'],
            ['code' => '30183', 'name' => 'STI College – Meycauayan'],
            ['code' => '30184', 'name' => 'STI College – San Fernando'],
            ['code' => '30185', 'name' => 'STI College – Sta. Maria'],
            ['code' => '30186', 'name' => 'STI College – San Jose'],
            ['code' => '30187', 'name' => 'STI College – Tarlac'],
            ['code' => '30188', 'name' => 'Sto. Rosario Sapang Palay College'],
            ['code' => '30189', 'name' => 'Subic Bay College, Inc.'],
            ['code' => '30190', 'name' => 'Systems Plus College Foundation, Inc.'],
            ['code' => '30191', 'name' => 'Tarlac Agricultural University (Formerly: Tarlac College of Agriculture)'],
            ['code' => '30192', 'name' => 'Tarlac Christian Colleges, Inc.'],
            ['code' => '30193', 'name' => 'Tarlac State University – Main Campus'],
            ['code' => '30194', 'name' => 'Tarlac State University – San Isidro Campus'],
            ['code' => '30195', 'name' => 'The Good Samaritan Colleges, Inc.'],
            ['code' => '30196', 'name' => 'The Manila Times College of Subic, Inc.'],
            ['code' => '30197', 'name' => 'Tomas Del Rosario College'],
            ['code' => '30198', 'name' => 'United School of Science And Technology Colleges'],
            ['code' => '30199', 'name' => 'University of the Assumption'],
            ['code' => '30200', 'name' => 'University of the Philippines – Diliman (Olongapo City)'],
            ['code' => '30201', 'name' => 'University of the Philippines – Diliman (Pampanga)'],
            ['code' => '30202', 'name' => 'Virgen Milagrosa Del Rosario College Seminary'],
            ['code' => '30203', 'name' => 'Wesleyan University-Philippines-Aurora'],
            ['code' => '30204', 'name' => 'Wesleyan University-Philippines-Cabanatuan City'],
            ['code' => '30205', 'name' => 'Westfields International College, Inc.'],
            ['code' => '30206', 'name' => 'World Citi Colleges-Guimba, Inc.'],
        ];
    }

}
